onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix hexadecimal /stimulus/key
add wave -noupdate -radix hexadecimal /stimulus/plaintext
add wave -noupdate -radix hexadecimal /stimulus/encrypt
add wave -noupdate -radix hexadecimal /stimulus/ciphertext
add wave -noupdate -radix hexadecimal /stimulus/clk
add wave -noupdate -radix hexadecimal /stimulus/errors
add wave -noupdate -radix hexadecimal /stimulus/vectornum
add wave -noupdate -radix hexadecimal /stimulus/result
add wave -noupdate -radix hexadecimal /stimulus/op
add wave -noupdate -radix hexadecimal /stimulus/handle3
add wave -noupdate -radix hexadecimal /stimulus/desc3
add wave -noupdate -radix hexadecimal /stimulus/i
add wave -noupdate -radix hexadecimal /stimulus/j
add wave -noupdate -radix hexadecimal /stimulus/dut/key
add wave -noupdate -radix hexadecimal /stimulus/dut/plaintext
add wave -noupdate -radix hexadecimal /stimulus/dut/encrypt
add wave -noupdate -radix hexadecimal /stimulus/dut/ciphertext
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey1
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey2
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey3
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey4
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey5
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey6
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey7
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey8
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey9
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey10
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey11
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey12
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey13
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey14
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey15
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKey16
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN1
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN2
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN3
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN4
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN5
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN6
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN7
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN8
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN9
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN10
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN11
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN12
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN13
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN14
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN15
add wave -noupdate -radix hexadecimal /stimulus/dut/SubKeyN16
add wave -noupdate -radix hexadecimal /stimulus/dut/round1out
add wave -noupdate -radix hexadecimal /stimulus/dut/round2out
add wave -noupdate -radix hexadecimal /stimulus/dut/round3out
add wave -noupdate -radix hexadecimal /stimulus/dut/round4out
add wave -noupdate -radix hexadecimal /stimulus/dut/round5out
add wave -noupdate -radix hexadecimal /stimulus/dut/round6out
add wave -noupdate -radix hexadecimal /stimulus/dut/round7out
add wave -noupdate -radix hexadecimal /stimulus/dut/round8out
add wave -noupdate -radix hexadecimal /stimulus/dut/round9out
add wave -noupdate -radix hexadecimal /stimulus/dut/round10out
add wave -noupdate -radix hexadecimal /stimulus/dut/round11out
add wave -noupdate -radix hexadecimal /stimulus/dut/round12out
add wave -noupdate -radix hexadecimal /stimulus/dut/round13out
add wave -noupdate -radix hexadecimal /stimulus/dut/round14out
add wave -noupdate -radix hexadecimal /stimulus/dut/round15out
add wave -noupdate -radix hexadecimal /stimulus/dut/round16out
add wave -noupdate -radix hexadecimal /stimulus/dut/ip_out
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/Key
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey1
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey2
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey3
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey4
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey5
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey6
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey7
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey8
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey9
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey10
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey11
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey12
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey13
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey14
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey15
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/SubKey16
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS1
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS2
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS3
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS4
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS5
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS6
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS7
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS8
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS9
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS10
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS11
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS12
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS13
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS14
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS15
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/LS16
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS1
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS2
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS3
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS4
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS5
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS6
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS7
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS8
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS9
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS10
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS11
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS12
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS13
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS14
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS15
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/RS16
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/permute1/key
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/permute1/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/permute1/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/permute1/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R1/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R1/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R1/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R1/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R2/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R2/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R2/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R2/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R3/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R3/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R3/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R3/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R4/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R4/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R4/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R4/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R5/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R5/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R5/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R5/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R6/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R6/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R6/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R6/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R7/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R7/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R7/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R7/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R8/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R8/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R8/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R8/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R9/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R9/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R9/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R9/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R10/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R10/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R10/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R10/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R11/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R11/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R11/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R11/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R12/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R12/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R12/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R12/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R13/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R13/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R13/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R13/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R14/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R14/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R14/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R14/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R15/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R15/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R15/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R15/block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R16/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R16/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R16/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/k1/PC2R16/block
add wave -noupdate -radix hexadecimal /stimulus/dut/b1/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/b1/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round1/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round2/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round3/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round4/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round5/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round6/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round7/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round8/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round9/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round10/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round11/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round12/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round13/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round14/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round15/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/right_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/left_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelOut
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/xor_out2
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/subkey
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/exp_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/xor_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s1_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s2_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s3_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s4_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s5_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s6_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s7_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s8_out
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/Sout
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/exp/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/exp/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s1box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s1box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s2box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s2box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s3box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s3box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s4box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s4box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s5box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s5box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s6box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s6box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s7box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s7box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s8box/inp_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/s8box/out_bits
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/straightDBox/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/round16/feistelBlock/straightDBox/out_block
add wave -noupdate -radix hexadecimal /stimulus/dut/FP/inp_block
add wave -noupdate -radix hexadecimal /stimulus/dut/FP/out_block
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {76315 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 350
configure wave -valuecolwidth 200
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {78750 ps}
